# apiVersion: v1
# kind: Service
# metadata:
#   name: alertmanager
#   namespace: monitoring
#   annotations:
#       prometheus.io/scrape: 'true'
#       prometheus.io/port:   '9093'
# spec:
#   selector: 
#     app: alertmanager
#   type: NodePort  
#   ports:
#     - port: 9093
#       targetPort: 9093
#       nodePort: 31000

apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  ports:
  - protocol: TCP
    port: 9093
    targetPort: 9093
